name: on PR to main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "epic/*" ]

env:
  BUILD_TYPE: Debug
  CONTAINER_SRC_DIR: /usr/app/src
  CONTAINER_BIN_DIR: /usr/app/bin
  WORKSPACE_BIN_DIR: ${{github.workspace}}/bin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: retrieve user and group id
      id: get_ids
      run: |
        echo "runner_uid=$(id -u)" >> $GITHUB_OUTPUT
        echo "runner_gid=$(id -g)" >> $GITHUB_OUTPUT

    - name: build dev image
      id: build_dev_image
      uses: docker/build-push-action@v3
      with:
        build-args: |
          UID=${{steps.get_ids.outputs.runner_uid}}
          GID=${{steps.get_ids.outputs.runner_gid}}
        tags: sdspidriverdev:latest
        file: ${{github.workspace}}/docker/dev.dockerfile

    - name: cmake config
      working-directory: ${{github.workspace}}
      run: |
        mkdir -p ${{env.WORKSPACE_BIN_DIR}}
        docker run -i -v ${{github.workspace}}:${{env.CONTAINER_SRC_DIR}} -v ${{env.WORKSPACE_BIN_DIR}}:${{env.CONTAINER_BIN_DIR}} ${{steps.build_dev_image.outputs.imageid}} -c "cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSDSPIDRIVER_TESTS=ON -DSDSPIDRIVER_LINUX_FEATURES=ON -S ${{env.CONTAINER_SRC_DIR}} -B ${{env.CONTAINER_BIN_DIR}}"
    
    - name: build
      working-directory: ${{github.workspace}}
      run: |
        docker run -i -v ${{github.workspace}}:${{env.CONTAINER_SRC_DIR}} -v ${{env.WORKSPACE_BIN_DIR}}:${{env.CONTAINER_BIN_DIR}} ${{steps.build_dev_image.outputs.imageid}} -c "cmake --build ${{env.CONTAINER_BIN_DIR}} -j $(nproc)"

    - name: run uts
      working-directory: ${{github.workspace}}
      run: |
        docker run -i -v ${{github.workspace}}:${{env.CONTAINER_SRC_DIR}} -v ${{env.WORKSPACE_BIN_DIR}}:${{env.CONTAINER_BIN_DIR}} -w ${{env.CONTAINER_BIN_DIR}} ${{steps.build_dev_image.outputs.imageid}} -c "ctest --rerun-failed --output-on-failure"